name: Deploy to Docker hub then Azure Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-push-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@master

      # grep the version from main.go, var AppVersion = "1.0.0", then cut the version number between the double quotes
      - name: "Get version"
        id: get_version
        run: echo "APP_VERSION=$(grep 'var AppVersion' main.go | cut -d '"' -f 2)" >> $GITHUB_ENV

      - name: "Login via Docker Hub"
        uses: docker/login-action@v2
        with:
          username: onlineeric
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Build and push Docker image"
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: onlineeric/eric-gin-server:latest, onlineeric/eric-gin-server:${{ env.APP_VERSION }}

  deploy-to-azure:
    needs: build-and-push-to-docker-hub
    runs-on: ubuntu-latest

    steps:
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "eric-gin-server"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
          images: onlineeric/eric-gin-server:latest
